### ISSUE TITLE
Move to OCA?

### ISSUE THREAD

**Issue by pedrobaeza** [muk-it/muk_dms#125]
Hello, have you thought about moving this under OCA umbrella? I think you are already used to Odoo + OCA ecosystem, so it's not needed to tell you about the advantages, but let me know if you have any fear or doubt about that.

**Comment by keshrath** [comment]
Hello, 

honestly, we've never really thought about it. Probably because we've started this project before we knew about the OCA ecosystem.

In the meanwhile we got familiar with the OCA and it would definitely be an interesting discussion that we should have internally. But I am not sure if this step would be the right one for us at the moment.

Two possible problems I see for us are on the one hand that all OCA modules are licensed under the AGPL and we've changed the license of the DMS to LGPL. By doing this we wanted to give others, but also ourselves the possibility to develop new modules on the basis of the DMS, without having to publish them under the AGPL. On the other hand the DMS is a good way for us to get attention and as far as I know there are no branded projects at OCA yet.

However, there is of course also an advantage of being closer to the OCA and this is certainly something we will discuss internally.

**Comment by pedrobaeza** [comment]
Hi, Mathias, thanks for answering!

Great to know that there's a possibility of moving it.

About the license, you don't have to worry: you can keep LGPL. OCA doesn't enforce to use AGPL. Most of the OCA developments are AGPL because developers choose to use that one for the maximum "openness", but OCA allows several open source license. See the section "Licenses & CLA" in https://odoo-community.org/page/faq. Check for example that most of the website modules are LGPL (my company Tecnativa publishes them under this license, as it's usual to mount private themes or customizations over it that you don't want to give the source code to any website visitor).

Let me know if you need any other clarification or want to have a direct conversation over hangouts or similar.

Happy Christmas!

**Comment by pedrobaeza** [comment]
Hello, did you talk about this internally? Any decision?

**Comment by satriani-vai** [comment]
I see this as a good chance to get more manpower for your project without losing your interests. You will be very relieved and can better focus on commercial goals.  It would be a wise decision to join the OCA.

**Comment by pedrobaeza** [comment]
Sorry for insisting, but I think it's very interesting to merge efforts in a community DMS. Do you want me to make the PRs to OCA with your authorization?

**Comment by pedrobaeza** [comment]
I hope all of you are OK in these hard days. This is only a friendly reminder to see if you have thought about this.

**Comment by mileo** [comment]
Any updates? Our team is available to assist in the migration of these modules to the community.

**Comment by pedrobaeza** [comment]
The move has been done for v13:

https://github.com/OCA/dms/pull/1

So we can close this.
