### ISSUE TITLE
[12.0] QUESTION: Any Roadmap for 12.0?

### ISSUE THREAD

**Issue by lukebranch** [muk-it/muk_dms#59]
Amazing contribution, thanks for keeping this open-source!

Do you have any roadmap for migration to Odoo 12.0 after it's released next month?

**Comment by keshrath** [comment]
We wanted to wait until it was clear if Odoos own DMS is available for the community version or only for the enterprise version. In case it is available in the community version, we would have built our DMS on top of it.

Meanwhile it's already merged into the enterprise master and I think you can safely assume that it will only be released for this version with Odoo 12.  

Since we want to make our modules available to the community, we will not aim to have any dependencies with an enterprise module. 

That means we will migrate our modules to version 12 and are already working on it. If you take a look around our Github you will see that there is already a 12 branch in some projects. Of course we are trying to do some improvements in the course of this, but basically not too much should change in the modules. But apart from the migration we are also working on the DMS. (see [1])

If you have any questions, I will be happy to answer them and since I have to rework the modules anyway during the migration, this is also an ideal time for feedback and wishes. :)

[1] https://mukit.at/en_US/blog/news-1/post/muk-documents-roadmap-5

**Comment by lukebranch** [comment]
Great news, thanks for the detailed reply!

In terms of feature wishlists/requests, i'd love to see version control, collaborative editing (this is incredibly tricky to achieve I know, but perhaps some form of integration with an existing suite like Collabora Online Development Edition?), and the possibility of creating actions within models (eg. sales.order) to automatically file documents created based on a predefined set of rules (eg. file by //Customer/SaleOrder/{{DOC_SEQUENCE}}.

To be honest it does appear that the Odoo Enterprise version has taken quite heavy inspiration from your DMS. Really great work from the MUK IT team, i've begun to use some of your preview widgets in a custom filing management system.

I look forward to seeing what you guys release in the 12.0 iteration!

**Comment by keshrath** [comment]
A Verion control is in progress and will be relaesed later with version 12 but will also be released for version 11. What exactly do you mean by this: Creating actions within models?
